---
title: "Auto-Antigen Levels Munich"
author: "Kerstin Rubarth"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: false
      smooth_scroll: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.path= "Files")
library(readxl)
library(tidyverse)
library(janitor)
library(limma)
library(FactoMineR)
library(factoextra)
library(patchwork)
library(EnhancedVolcano)
library(tableone)
library(kableExtra)
library(dplyr)
library(openxlsx)
library(viridis)
library(forcats)
library(grid)
library(gridExtra)
library(ggpubr)
library(Hmisc)
library(ggh4x)
library(psych)
library(reshape2)
```

```{r data}
data <- read_excel("../cohort/Supplemental_table_1.xlsx",sheet = "protein-IgG")
names <- data[1,]
data <- data[-1,]

colnames(data) <- names
data <- clean_names(data)

names <- colnames(data)
names <- gsub("median_pe_", "", names)
names <- gsub("labim_", "", names)
names <- gsub("labinf_", "", names)
names <- gsub("labend_", "", names)
names <- gsub("labkl_", "", names)
names <- gsub("labh_","", names)
names <- gsub("_altes_peptid", "", names)
names <- gsub("response" ,"", names)
names <- gsub("__afu", "", names)
names <- gsub("ebv_serology_", "", names)


colnames(data) <- names

igG_M <- c("ebna3c_ebna6_ig_g", "adra1b_ig_g", "adra1d_ig_g", "adra2c_ig_g", "pld6_ig_g", "srrm3_ig_g", "slc24a3_ig_g", "tspyl2_ig_g", "ebna3b_ebna4_ig_g", "tspyl5_ig_g")

## Scores
scores <- c("fatigue_score",
                        "cognitive_score",
                        "severity_of_muscle_pain_sy_6",
                        "severity_of_headache_sy_7",
                        "pem_score",
                        "com_total")

data[c(igG_M, scores)] <- lapply(data[c(igG_M, scores)], as.numeric)




data <- data %>% mutate(diagnosis = case_when(diagnosis == "PCS" ~ "PCS",
                                              diagnosis == "piCFS" ~ "piMECFS",
                                              diagnosis == "pcCFS" ~ "pcMECFS",
                                              diagnosis == "HC" ~ "HC"))


```


```{r heatmap_func, fig.width=8, fig.height=8, out.width='70%', fig.align='center',results='asis'}
create_correlation_plot <- function(data, v1, v2, d, stratified, show_legend = TRUE, show_y_labels = TRUE) {


  
  if(identical(deparse(substitute(v2)), "igG_M")){
    custom_labels2 <- c("ebna3c_ebna6_ig_g" = "EBNA6",
                        "adra1b_ig_g" = "ADRA1B",
                        "adra1d_ig_g" = "ADRA1D",
                        "adra2c_ig_g" = "ADRA2C",
                        "pld6_ig_g" = "PLD6",
                        "srrm3_ig_g" = "SRRM3",
                        "slc24a3_ig_g" = "SLC24A3",
                        "tspyl2_ig_g" = "TSPYL2",
                        "ebna3b_ebna4_ig_g" = "EBNA4",
                        "tspyl5_ig_g" = "TSPYL5"
                        )
  }


  

  

  
    if(identical(deparse(substitute(v2)), "scores")){
    custom_labels2 <- c("fatigue_score" = "Fatigue",
                        "cognitive_score" = "Cognition",
                        "severity_of_muscle_pain_sy_6" = "Muscle Pain",
                        "severity_of_headache_sy_7" = "Headache",
                        "pem_score" = "PEM",
                        "com_total" = "Compass")
  }  
    
  
  
 
  
  if(identical(deparse(substitute(v1)), "igG_M")){
    custom_labels1 <- c("ebna3c_ebna6_ig_g" = "EBNA6",
                        "adra1b_ig_g" = "ADRA1B",
                        "adra1d_ig_g" = "ADRA1D",
                        "adra2c_ig_g" = "ADRA2C",
                        "pld6_ig_g" = "PLD6",
                        "srrm3_ig_g" = "SRRM3",
                        "slc24a3_ig_g" = "SLC24A3",
                        "tspyl2_ig_g" = "TSPYL2",
                        "ebna3b_ebna4_ig_g" = "EBNA4",
                        "tspyl5_ig_g" = "TSPYL5"
                        )
  }
 
  



  
  if(identical(deparse(substitute(v1)), "scores")){
    custom_labels1 <- c("fatigue_score" = "Fatigue",
                        "cognitive_score" = "Cognition",
                        "severity_of_muscle_pain_sy_6" = "Muscle Pain",
                        "severity_of_headache_sy_7" = "Headache",
                        "pem_score" = "PEM",
                        "com_total" = "Compass")
  }    
  
    
 
  custom_labels2 <- rev(custom_labels2)

    if (stratified) {
    data_sub <- subset(data, diagnosis == d)
  } else {
    data_sub <- subset(data, diagnosis != "piMECFS")
  }
  
  
  
  # Calculate Correlations
  cor_mat <- cor(data_sub[, v1, drop = FALSE], data_sub[, v2, drop = FALSE], use = "pairwise.complete.obs", method = "spearman")
  cor_mat <- as.data.frame(cor_mat)

  # Initialize DataFrame for p-values and sample sizes
  p_values <- matrix(NA, ncol = length(v2), nrow = length(v1))
  n_values <- matrix(NA, ncol = length(v2), nrow = length(v1))
  colnames(p_values) <- colnames(cor_mat)
  rownames(p_values) <- rownames(cor_mat)
  colnames(n_values) <- colnames(cor_mat)
  rownames(n_values) <- rownames(cor_mat)

 for(i in seq_along(v1)) {
    for(j in seq_along(v2)) {
        x <- as.numeric(unlist(data_sub[, v1[i]]))
        y <- as.numeric(unlist(data_sub[, v2[j]]))
        
        # Calculate the number of non-missing values in both x and y
        n_values[i, j] <- sum(!is.na(x) & !is.na(y))
        
        # Only perform the correlation test if there are valid pairs
        if (n_values[i, j] > 0) {
            test <- cor.test(x, y, method = "spearman", use = "pairwise.complete.obs")
            p_values[i, j] <- test$p.value
        } else {
            p_values[i, j] <- NA
        }
    }
}
  p_values <- as.data.frame(p_values)
  n_values <- as.data.frame(n_values)

  # Format Correlations, p-values, and n-values into a suitable format
  cor_mat <- cor_mat %>%
    rownames_to_column(var = "Var1") %>%
    gather(key = "Var2", value = "Correlation", -Var1) %>%
    mutate(
      Var1 = recode_factor(Var1, !!!custom_labels1),
      Var2 = recode_factor(Var2, !!!custom_labels2)
    )

  p_values <- p_values %>%
    rownames_to_column(var = "Var1") %>%
    gather(key = "Var2", value = "p_value", -Var1) %>%
    mutate(
      Var1 = recode_factor(Var1, !!!custom_labels1),
      Var2 = recode_factor(Var2, !!!custom_labels2)
    )

  n_values <- n_values %>%
    rownames_to_column(var = "Var1") %>%
    gather(key = "Var2", value = "n", -Var1) %>%
    mutate(
      Var1 = recode_factor(Var1, !!!custom_labels1),
      Var2 = recode_factor(Var2, !!!custom_labels2)
    )

  result <- left_join(cor_mat, p_values, by = c("Var1", "Var2"))
  result <- left_join(result, n_values, by = c("Var1", "Var2"))

  # Create a new field for the star based on the p-value
  result <- result %>%
    mutate(Star = ifelse(p_value < 0.05, "*", ""))
  
  
   # Calculate the number of variables
  n_var1 <- length(v1)
  n_var2 <- length(v2)

  # Set tile size (adjust as needed)
  tile_size <- 0.35

  # Calculate the plot dimensions based on the number of variables and tile size
  plot_width <- tile_size * n_var1   
  plot_height <- tile_size * n_var2
  
  
  
  # Create the plot
  g <- ggplot(data = result, 
              aes(Var1, Var2, fill = Correlation)) +
    geom_tile(color = "white") +
    scale_fill_gradient2(low = "red", mid = "white", high = "blue", 
                         midpoint = 0, limit = c(-1, 1), space = "Lab", 
                         name = "Correlation") +
    theme_minimal() +
    theme(
      axis.text.y = if (show_y_labels) element_text(hjust = 1, face = "bold", size = 10) else element_blank(),
    legend.position = if (show_legend) "right" else "none",  # Steuert die Legende

      axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 0, face = "bold", size = 10),  
      #axis.text.y = element_text(hjust = 1, face = "bold", size = 10),  
      axis.title.x = element_text(vjust = 1.5, face = "bold", size = 10),  # Adjust x-axis title position
      axis.title.y = element_blank(),
      panel.grid.major = element_blank(),
      panel.border = element_blank(),
      panel.background = element_blank(),
      axis.ticks = element_blank(),
      #plot.margin = margin(1, 1, 1, 1, "cm"),  # Adjust the margin around the plot
      panel.spacing = unit(0.5, "lines"),
    plot.title = element_text(hjust = 0.5, size = 26, 
                                    face = "plain", # Kein fettgedruckter Titel
                                    family = "Times New Roman")
    ) +  
    labs(title = paste(d)) +
    geom_text(aes(Var1, Var2, label = ifelse(abs(Correlation) > 0.7, sprintf("%.2f\nn=%d", Correlation, n), "")),
              color = "white", size = 3) +
    geom_text(aes(Var1, Var2, label = ifelse(abs(Correlation) <= 0.7 & abs(Correlation) > 0.3, sprintf("%.2f\nn=%d", Correlation, n), "")),
              color = "black", size = 3) +
    scale_x_discrete(labels = custom_labels1, position = "top") + 
    scale_y_discrete(labels = custom_labels2) +
    labs(x = NULL) +
    geom_text(aes(label = Star), color = "black", size = 5, vjust = +0.8, hjust = -1.5)+
    force_panelsizes(cols = unit(plot_width, "in"), rows = unit(plot_height, "in"))
  
  print(g)
  
  # Create a folder for saved graphics (if not already present)
  save_folder <- "Heatmaps2"
  if (!file.exists(save_folder)) {
    dir.create(save_folder)
  }

  # Generate filename for saved graphic
  file_name <- paste(save_folder, "/", deparse(substitute(v1)), "_", deparse(substitute(v2)),"_", gsub("/", "_", d), "_correlation_plot.png", sep = "")

 # print(file_name)
  # Save graphic
  ggsave(file_name, g, width = plot_width +2, height = plot_height+2, bg = "white", limitsize = FALSE)
  return(g)
}
```





## Correlation with Clinical Scores

```{r igM_scores, fig.width=10, fig.height=10, out.width='70%', fig.align='center',results='asis'}
dia <- c("PCS", "pcMECFS", "piMECFS")
for(d in dia){
  create_correlation_plot(data, igG_M, scores, d, TRUE, TRUE, TRUE)
}
```



